############################
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!
#
# WARNING : MANAGED BY ANSIBLE, CHANGES MADE HERE
# MAY BE OVERWRITTEN AT ANY TIME
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!
#
############################

logLevel = "INFO"
#logLevel = "ERROR"
#logLevel = "DEBUG"

defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    # Redirect to HTTPS on HTTP connections
    [entryPoints.http.redirect]
      entryPoint = "https"


  [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]


[acme]
email = "{{ le_email }}"
storage = "/data/acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false
[acme.httpChallenge]
  entryPoint = "http"


[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "{{ app.domain }}"
watch = true
exposedByDefault = false
